# https://yazi-rs.github.io/docs/configuration/yazi/
[mgr]
linemode = "size_and_mtime"
show_hidden = true
sort_dir_first = true
show_symlink = true

[preview]
wrap = "yes"
tab_size = 4
image_filter = "lanczos3" # alt: nearest triangle catmull-rom
image_quality = 90 # range: 50–90
image_delay = 50 # max: 100
# ueberzug_offset = [1, 1, 1, 1]
