name: spec-driven
version: 1
description: Custom workflow schema for spec-driven
artifacts:
  - id: proposal
    generates: proposal.md
    description: High-level description of the change, its motivation, and scope
    template: proposal.md
    requires: []
  - id: specs
    generates: specs/**/*.md
    description: Detailed specifications with requirements and scenarios
    template: specs/spec.md
    requires:
      - proposal
  - id: design
    generates: design.md
    description: Technical design decisions and implementation approach
    template: design.md
    requires:
      - specs
  - id: tasks
    generates: tasks.md
    description: Implementation checklist with trackable tasks
    template: tasks.md
    requires:
      - design
apply:
  requires:
    - tasks
  tracks: tasks.md
